extends Node


# warning-ignore:unused_signal
signal update_health
# warning-ignore:unused_signal
signal update_mana
# warning-ignore:unused_signal
signal update_exp
# warning-ignore:unused_signal
signal update_level
# warning-ignore:unused_signal
signal update_displayname
# warning-ignore:unused_signal
signal fail_login
# warning-ignore:unused_signal
signal dialog_closed
# warning-ignore:unused_signal
signal update_inventory
# warning-ignore:unused_signal
signal log_out
# warning-ignore:unused_signal
signal update_stats
# warning-ignore:unused_signal
signal level_up
# warning-ignore:unused_signal
signal toggle_inventory
# warning-ignore:unused_signal
signal toggle_stats
# warning-ignore:unused_signal
signal toggle_options
# warning-ignore:unused_signal
signal toggle_chat_group
# warning-ignore:unused_signal
signal send_message
# warning-ignore:unused_signal
signal toggle_option_bool
# warning-ignore:unused_signal
signal drop_quantity
# warning-ignore:unused_signal
signal toggle_skills
# warning-ignore:unused_signal
signal update_skills
# warning-ignore:unused_signal
signal toggle_keybinds
# warning-ignore:unused_signal
signal update_keybinds
# warning-ignore:unused_signal
signal attack
# warning-ignore:unused_signal
signal use_skill
# warning-ignore:unused_signal
signal take_damage
# warning-ignore:unused_signal
signal update_equipment
# warning-ignore:unused_signal
signal toggle_equipment
# warning-ignore:unused_signal
signal update_sprite
# warning-ignore:unused_signal
signal reset_default_keybind
# warning-ignore:unused_signal
signal key_in_use
# warning-ignore:unused_signal
signal server_offline
# warning-ignore:unused_signal
signal scene_loaded
# warning-ignore:unused_signal
signal connection_unsuccessful

# Called when the node enters the scene tree for the first time.
func _ready():
	pass # Replace with function body.
